services:

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-service:
    build: .
    container_name: backend-service
    restart: always
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3
    volumes:
      - .:/app

networks:
  backend: {}

volumes:
  postgres_data: {}